import { describe, expect, it } from "vitest";
import {
  decryptText,
  encryptText,
  parseMetadata,
  reencryptText
} from "../src/dotseal/core";
import {
  decryptValue,
  encryptValue,
  keyFingerprint,
  loadKeyBytes
} from "../src/dotseal/crypto";
import { parse, serialize, formatValue } from "../src/dotseal/parser";

const keyBytes = loadKeyBytes(Buffer.alloc(32, 1).toString("base64"));

describe("dotseal crypto", () => {
  it("encrypts and decrypts a value with AAD binding", () => {
    const token = encryptValue(keyBytes, "super-secret", "API_KEY");

    expect(token).toMatch(/^ENC\[AES_GCM,data:.+\]$/);
    expect(decryptValue(keyBytes, token, "API_KEY")).toBe("super-secret");
    expect(() => decryptValue(keyBytes, token, "OTHER_KEY")).toThrow(
      /wrong key, corrupted data, or the value was moved/
    );
  });

  it("round-trips an empty value", () => {
    const token = encryptValue(keyBytes, "", "EMPTY");

    expect(token).toMatch(/^ENC\[AES_GCM,data:.+\]$/);
    expect(decryptValue(keyBytes, token, "EMPTY")).toBe("");
  });

  it("matches the Python key fingerprint contract", () => {
    expect(keyFingerprint(keyBytes)).toBe("5ec6bb135ca102fd");
  });
});

describe("dotseal parser", () => {
  it("preserves structure and normalizes values like the Python parser", () => {
    const parsed = parse("# hello\nexport API_KEY = \"line\\nvalue\"\nEMPTY=\n\n");

    expect(parsed.records).toEqual([
      { kind: "comment", raw: "# hello", key: "", value: "", export: false, comment: "" },
      {
        kind: "entry",
        raw: "",
        key: "API_KEY",
        value: "line\nvalue",
        export: true,
        comment: ""
      },
      { kind: "entry", raw: "", key: "EMPTY", value: "", export: false, comment: "" },
      { kind: "blank", raw: "", key: "", value: "", export: false, comment: "" }
    ]);
    expect(serialize(parsed)).toBe("# hello\nexport API_KEY=line\nvalue\nEMPTY=\n\n");
    expect(formatValue(" leading # value")).toBe("\" leading # value\"");
    expect(formatValue("simple")).toBe("simple");
  });

  it("strips whitespace-prefixed inline comments from unquoted values", () => {
    const parsed = parse("FOO=bar # production key\nPASS=ab#cd\n");

    expect(parsed.records[0]).toMatchObject({ key: "FOO", value: "bar", comment: " # production key" });
    expect(parsed.records[1]).toMatchObject({ key: "PASS", value: "ab#cd", comment: "" });
    expect(serialize(parsed)).toBe("FOO=bar # production key\nPASS=ab#cd\n");
  });
});

describe("dotseal core", () => {
  it("encrypts and decrypts whole .env text", () => {
    const cleartext = "# user comment\nDATABASE_URL=postgres://example\nDEBUG=True\n";
    const encrypted = encryptText(cleartext, keyBytes);

    expect(encrypted).toContain("# Generated by dotseal. DO NOT EDIT VALUES MANUALLY.");
    expect(encrypted).toContain("# dotseal: v=1 alg=AES_GCM key_fp=5ec6bb135ca102fd");
    expect(encrypted).toContain("DATABASE_URL=ENC[AES_GCM,data:");
    expect(parseMetadata(parse(encrypted)).get("key_fp")).toBe("5ec6bb135ca102fd");
    expect(decryptText(encrypted, keyBytes)).toBe(cleartext);
  });

  it("round-trips empty values through whole-file encryption", () => {
    const cleartext = "API_KEY=secret\nEMPTY=\n";
    const encrypted = encryptText(cleartext, keyBytes);

    expect(encrypted).toContain("EMPTY=ENC[AES_GCM,data:");
    expect(decryptText(encrypted, keyBytes)).toBe(cleartext);
  });

  it("does not keep a trailing blank line before the metadata", () => {
    const encrypted = encryptText("A=1\n\n", keyBytes);

    expect(encrypted).not.toMatch(/\n\n# dotseal:/);
  });

  it("supports selective encryption via plain keys", () => {
    const encrypted = encryptText("PUBLIC=ok\nSECRET=shh\n", keyBytes, {
      plainKeys: ["PUBLIC"]
    });

    expect(encrypted).toContain("PUBLIC=ok");
    expect(encrypted).toContain("SECRET=ENC[AES_GCM,data:");
    expect(encrypted).toContain("plain_keys=PUBLIC");
  });

  it("supports selective encryption via regex", () => {
    const encrypted = encryptText("PUBLIC_A=ok\nPUBLIC_B=ok\nSECRET=shh\n", keyBytes, {
      plainKeyRegex: ["PUBLIC_.+"]
    });

    expect(encrypted).toContain("PUBLIC_A=ok");
    expect(encrypted).toContain("PUBLIC_B=ok");
    expect(encrypted).toContain("SECRET=ENC[AES_GCM,data:");
    expect(encrypted).toContain("plain_re=");
  });

  it("handles alternation regex correctly (fullmatch semantics)", () => {
    // Pattern "ENV|ENV_VAR": key ENV_VAR must match fully.
    // A leftmost-match simulation would wrongly match "ENV" and consider
    // ENV_VAR encrypted; anchored ^(?:...)$ tries all alternatives at full length.
    const encrypted = encryptText("ENV=x\nENV_VAR=y\nSECRET=z\n", keyBytes, {
      plainKeyRegex: ["ENV|ENV_VAR"]
    });

    expect(encrypted).toContain("ENV=x");
    expect(encrypted).toContain("ENV_VAR=y");
    expect(encrypted).toContain("SECRET=ENC[AES_GCM,data:");
  });

  it("skips Python-only regex syntax in footer without crashing", () => {
    // Create a properly encrypted file, then inject a Python-specific named-group
    // pattern into the footer ((?P<name>ENV_.+) — valid Python, invalid JS).
    // base64url("(?P<name>ENV_.+)") = "KD9QPG5hbWU-RU5WXy4rKQ"
    const base = encryptText("ENV_VAR=original\nSECRET=shh\n", keyBytes);
    const withPythonRegex = base.replace(
      new RegExp(`# dotseal: v=1 alg=AES_GCM key_fp=\\S+`),
      `# dotseal: v=1 alg=AES_GCM key_fp=${keyFingerprint(keyBytes)} plain_re=KD9QPG5hbWU-RU5WXy4rKQ`
    );

    // reencryptText must not throw; the Python-only pattern is silently skipped
    // so all keys are encrypted (fail-closed).
    expect(() =>
      reencryptText("ENV_VAR=newval\nSECRET=newshh\n", keyBytes, withPythonRegex)
    ).not.toThrow();

    const result = reencryptText("ENV_VAR=newval\nSECRET=newshh\n", keyBytes, withPythonRegex);
    // Pattern was skipped → both keys are encrypted (fail-closed).
    expect(result).toContain("ENV_VAR=ENC[AES_GCM,data:");
    expect(result).toContain("SECRET=ENC[AES_GCM,data:");
  });
});

describe("dotseal core re-encryption guards", () => {
  const otherKey = loadKeyBytes(Buffer.alloc(32, 2).toString("base64"));

  it("refuses to re-encrypt a file made with a different key", () => {
    const encrypted = encryptText("FOO=bar\n", keyBytes);

    expect(() => encryptText(encrypted, otherKey)).toThrow(/does not match/);
  });

  it("is idempotent when re-encrypting with the same key", () => {
    const encrypted = encryptText("FOO=bar\n", keyBytes);

    expect(decryptText(encryptText(encrypted, keyBytes), keyBytes)).toBe("FOO=bar\n");
  });

  it("rejects ENC lookalike values without dotseal metadata", () => {
    expect(() => encryptText("SNEAKY=ENC[AES_GCM,data:aGVsbG8=]\n", keyBytes)).toThrow(
      /cannot be verified/
    );
  });

  it("rejects asymmetric (v=2) files with a clear message", () => {
    const asym =
      "FOO=ENC[AES_GCM,data:aGVsbG8=]\n" +
      "# dotseal:recipient fp=abc ephem=def enc=ghi\n" +
      "# dotseal: v=2 alg=AES_GCM+X25519\n";

    expect(() => decryptText(asym, keyBytes)).toThrow(/asymmetric/);
    expect(() => encryptText(asym, keyBytes)).toThrow(/asymmetric/);
  });

  it("parseMetadata skips recipient lines and reads the footer", () => {
    const asym =
      "# dotseal:recipient fp=abc ephem=def enc=ghi\n" +
      "# dotseal: v=2 alg=AES_GCM+X25519\n";
    const meta = parseMetadata(parse(asym));

    expect(meta.get("v")).toBe("2");
    expect(meta.get("fp")).toBeUndefined();
  });

  it("parseMetadata ignores user comments that start with # dotseal:", () => {
    const encrypted = encryptText("FOO=bar\n", keyBytes);
    const tampered = "# dotseal: managed file, do not touch\n" + encrypted;
    const meta = parseMetadata(parse(tampered));

    expect(meta.get("v")).toBe("1");
    expect(meta.get("key_fp")).toBe("5ec6bb135ca102fd");
  });
});

describe("dotseal core reencryptText", () => {
  it("reuses ciphertexts for unchanged values", () => {
    const original = encryptText("KEEP=same\nCHANGE=old\n", keyBytes);
    const tokens = new Map(
      parse(original).records.filter((r) => r.kind === "entry").map((r) => [r.key, r.value])
    );

    const result = reencryptText("KEEP=same\nCHANGE=new\n", keyBytes, original);
    const newTokens = new Map(
      parse(result).records.filter((r) => r.kind === "entry").map((r) => [r.key, r.value])
    );

    expect(newTokens.get("KEEP")).toBe(tokens.get("KEEP"));
    expect(newTokens.get("CHANGE")).not.toBe(tokens.get("CHANGE"));
    expect(decryptText(result, keyBytes)).toBe("KEEP=same\nCHANGE=new\n");
  });

  it("preserves selective encryption policy by default", () => {
    const original = encryptText("PUBLIC=old\nSECRET=old\n", keyBytes, {
      plainKeys: ["PUBLIC"]
    });
    const result = reencryptText("PUBLIC=new\nSECRET=new\n", keyBytes, original);

    expect(result).toContain("PUBLIC=new");
    expect(result).toContain("SECRET=ENC[AES_GCM,data:");
    expect(result).toContain("plain_keys=PUBLIC");
  });

  it("merges unspecified policy dimensions on partial override", () => {
    const original = encryptText("FOO=old\nPUBLIC_EXTRA=old\nSECRET=old\n", keyBytes, {
      plainKeys: ["FOO"],
      plainKeyRegex: ["PUBLIC_.+"]
    });
    const result = reencryptText(
      "FOO=still\nPUBLIC_EXTRA=still\nSECRET=still\n",
      keyBytes,
      original,
      { plainKeys: ["BAR"] }
    );

    expect(result).toContain("FOO=ENC[AES_GCM,data:");
    expect(result).toContain("PUBLIC_EXTRA=still");
    expect(result).toContain("plain_re=");
    expect(result).toContain("plain_keys=BAR");
  });

  it("refuses a wrong key via the fingerprint", () => {
    const otherKey = loadKeyBytes(Buffer.alloc(32, 2).toString("base64"));
    const original = encryptText("FOO=bar\n", keyBytes);

    expect(() => reencryptText("FOO=baz\n", otherKey, original)).toThrow(/does not match/);
  });

  it("refuses asymmetric originals", () => {
    const asym =
      "FOO=ENC[AES_GCM,data:aGVsbG8=]\n" +
      "# dotseal:recipient fp=abc ephem=def enc=ghi\n" +
      "# dotseal: v=2 alg=AES_GCM+X25519\n";

    expect(() => reencryptText("FOO=baz\n", keyBytes, asym)).toThrow(/asymmetric/);
  });
});
