import { describe, expect, it } from "vitest";
import {
  decryptText,
  encryptText,
  parseMetadata
} from "../src/dotseal/core";
import {
  decryptValue,
  encryptValue,
  keyFingerprint,
  loadKeyBytes
} from "../src/dotseal/crypto";
import { parse, serialize, formatValue } from "../src/dotseal/parser";

const keyBytes = loadKeyBytes(Buffer.alloc(32, 1).toString("base64"));

describe("dotseal crypto", () => {
  it("encrypts and decrypts a value with AAD binding", () => {
    const token = encryptValue(keyBytes, "super-secret", "API_KEY");

    expect(token).toMatch(/^ENC\[AES_GCM,data:.+\]$/);
    expect(decryptValue(keyBytes, token, "API_KEY")).toBe("super-secret");
    expect(() => decryptValue(keyBytes, token, "OTHER_KEY")).toThrow(
      "Invalid Master Key or Corrupted Data."
    );
  });

  it("round-trips an empty value", () => {
    const token = encryptValue(keyBytes, "", "EMPTY");

    expect(token).toMatch(/^ENC\[AES_GCM,data:.+\]$/);
    expect(decryptValue(keyBytes, token, "EMPTY")).toBe("");
  });

  it("matches the Python key fingerprint contract", () => {
    expect(keyFingerprint(keyBytes)).toBe("5ec6bb135ca102fd");
  });
});

describe("dotseal parser", () => {
  it("preserves structure and normalizes values like the Python parser", () => {
    const parsed = parse("# hello\nexport API_KEY = \"line\\nvalue\"\nEMPTY=\n\n");

    expect(parsed.records).toEqual([
      { kind: "comment", raw: "# hello", key: "", value: "", export: false },
      { kind: "entry", raw: "", key: "API_KEY", value: "line\nvalue", export: true },
      { kind: "entry", raw: "", key: "EMPTY", value: "", export: false },
      { kind: "blank", raw: "", key: "", value: "", export: false }
    ]);
    expect(serialize(parsed)).toBe("# hello\nexport API_KEY=line\nvalue\nEMPTY=\n\n");
    expect(formatValue(" leading # value")).toBe("\" leading # value\"");
    expect(formatValue("simple")).toBe("simple");
  });
});

describe("dotseal core", () => {
  it("encrypts and decrypts whole .env text", () => {
    const cleartext = "# user comment\nDATABASE_URL=postgres://example\nDEBUG=True\n";
    const encrypted = encryptText(cleartext, keyBytes);

    expect(encrypted).toContain("# Generated by dotseal. DO NOT EDIT VALUES MANUALLY.");
    expect(encrypted).toContain("# dotseal: v=1 alg=AES_GCM key_fp=5ec6bb135ca102fd");
    expect(encrypted).toContain("DATABASE_URL=ENC[AES_GCM,data:");
    expect(parseMetadata(parse(encrypted)).get("key_fp")).toBe("5ec6bb135ca102fd");
    expect(decryptText(encrypted, keyBytes)).toBe(cleartext);
  });

  it("round-trips empty values through whole-file encryption", () => {
    const cleartext = "API_KEY=secret\nEMPTY=\n";
    const encrypted = encryptText(cleartext, keyBytes);

    expect(encrypted).toContain("EMPTY=ENC[AES_GCM,data:");
    expect(decryptText(encrypted, keyBytes)).toBe(cleartext);
  });

  it("does not keep a trailing blank line before the metadata", () => {
    const encrypted = encryptText("A=1\n\n", keyBytes);

    expect(encrypted).not.toMatch(/\n\n# dotseal:/);
  });
});
