import * as fs from "node:fs";
import * as path from "node:path";
import { spawnSync } from "node:child_process";
import { describe, expect, it } from "vitest";
import {
  decryptText,
  encryptText,
  parseMetadata
} from "../src/dotseal/core";
import {
  decryptValue,
  encryptValue,
  keyFingerprint,
  loadKeyBytes
} from "../src/dotseal/crypto";
import { parse, serialize, formatValue } from "../src/dotseal/parser";

const keyString = Buffer.alloc(32, 1).toString("base64");
const keyBytes = loadKeyBytes(keyString);
const repoRoot = path.resolve(__dirname, "../../..");

describe("dotseal crypto", () => {
  it("encrypts and decrypts a value with AAD binding", () => {
    const token = encryptValue(keyBytes, "super-secret", "API_KEY");

    expect(token).toMatch(/^ENC\[AES_GCM,data:.+\]$/);
    expect(decryptValue(keyBytes, token, "API_KEY")).toBe("super-secret");
    expect(() => decryptValue(keyBytes, token, "OTHER_KEY")).toThrow(
      "Invalid Master Key or Corrupted Data."
    );
  });

  it("round-trips an empty value", () => {
    const token = encryptValue(keyBytes, "", "EMPTY");

    expect(token).toMatch(/^ENC\[AES_GCM,data:.+\]$/);
    expect(decryptValue(keyBytes, token, "EMPTY")).toBe("");
  });

  it("matches the Python key fingerprint contract", () => {
    expect(keyFingerprint(keyBytes)).toBe("5ec6bb135ca102fd");
  });
});

describe("dotseal parser", () => {
  it("preserves structure and normalizes values like the Python parser", () => {
    const parsed = parse("# hello\nexport API_KEY = \"line\\nvalue\"\nEMPTY=\n\n");

    expect(parsed.records).toEqual([
      { kind: "comment", raw: "# hello", key: "", value: "", export: false },
      { kind: "entry", raw: "", key: "API_KEY", value: "line\nvalue", export: true },
      { kind: "entry", raw: "", key: "EMPTY", value: "", export: false },
      { kind: "blank", raw: "", key: "", value: "", export: false }
    ]);
    expect(serialize(parsed)).toBe("# hello\nexport API_KEY=line\nvalue\nEMPTY=\n\n");
    expect(formatValue(" leading # value")).toBe("\" leading # value\"");
    expect(formatValue("simple")).toBe("simple");
  });
});

describe("dotseal core", () => {
  it("encrypts and decrypts whole .env text", () => {
    const cleartext = "# user comment\nDATABASE_URL=postgres://example\nDEBUG=True\n";
    const encrypted = encryptText(cleartext, keyBytes);

    expect(encrypted).toContain("# Generated by dotseal. DO NOT EDIT VALUES MANUALLY.");
    expect(encrypted).toContain("# dotseal: v=1 alg=AES_GCM key_fp=5ec6bb135ca102fd");
    expect(encrypted).toContain("DATABASE_URL=ENC[AES_GCM,data:");
    expect(parseMetadata(parse(encrypted)).get("key_fp")).toBe("5ec6bb135ca102fd");
    expect(decryptText(encrypted, keyBytes)).toBe(cleartext);
  });

  it("round-trips empty values through whole-file encryption", () => {
    const cleartext = "API_KEY=secret\nEMPTY=\n";
    const encrypted = encryptText(cleartext, keyBytes);

    expect(encrypted).toContain("EMPTY=ENC[AES_GCM,data:");
    expect(decryptText(encrypted, keyBytes)).toBe(cleartext);
  });

  it("does not keep a trailing blank line before the metadata", () => {
    const encrypted = encryptText("A=1\n\n", keyBytes);

    expect(encrypted).not.toMatch(/\n\n# dotseal:/);
  });
});

describe("Python conformance", () => {
  it("decrypts TypeScript-encrypted text with Python", () => {
    const cleartext = "# user comment\nDATABASE_URL=postgres://example\nDEBUG=True\n";
    const encrypted = encryptText(cleartext, keyBytes);
    const decrypted = runPython("decrypt", encrypted);

    expect(decrypted).toBe(cleartext);
  });

  it("decrypts Python-encrypted text with TypeScript", () => {
    const cleartext = "# user comment\nDATABASE_URL=postgres://example\nDEBUG=True\n";
    const encrypted = runPython("encrypt", cleartext);

    expect(decryptText(encrypted, keyBytes)).toBe(cleartext);
  });

  it("agrees with Python on empty values in both directions", () => {
    const cleartext = "API_KEY=secret\nEMPTY=\n";

    expect(runPython("decrypt", encryptText(cleartext, keyBytes))).toBe(cleartext);
    expect(decryptText(runPython("encrypt", cleartext), keyBytes)).toBe(cleartext);
  });
});

function runPython(mode: "encrypt" | "decrypt", input: string): string {
  const python = findPython();
  const script = [
    "import sys",
    "from dotseal import core, crypto",
    "key = crypto.load_key_bytes(sys.argv[2])",
    "text = sys.stdin.read()",
    "if sys.argv[1] == 'encrypt':",
    "    sys.stdout.write(core.encrypt_text(text, key))",
    "elif sys.argv[1] == 'decrypt':",
    "    sys.stdout.write(core.decrypt_text(text, key))",
    "else:",
    "    raise SystemExit(2)"
  ].join("\n");

  const result = spawnSync(python, ["-c", script, mode, keyString], {
    cwd: repoRoot,
    input,
    encoding: "utf8"
  });

  if (result.status !== 0) {
    throw new Error(result.stderr || `Python exited with ${result.status}`);
  }

  return result.stdout;
}

function findPython(): string {
  if (process.env.DOTSEAL_PYTHON) {
    return process.env.DOTSEAL_PYTHON;
  }
  const venvPython = path.join(repoRoot, ".venv", "bin", "python");
  if (fs.existsSync(venvPython)) {
    return venvPython;
  }
  return "python3";
}
