"""High-level orchestration: key resolution and whole-file transforms.

This ties together :mod:`dotseal.crypto` (primitives) and
:mod:`dotseal.parser` (structure) into the operations the CLI and the
runtime loader actually need:

* find the master key (explicit arg -> env var -> local key file),
* encrypt / decrypt an entire file's text while preserving structure,
* embed and verify a key fingerprint so a wrong key fails fast.
"""

from __future__ import annotations

import base64
import contextlib
import os
import re
import tempfile
from typing import Dict, List, Optional, Pattern, Set, Tuple

from . import crypto, parser
from .exceptions import (
    DecryptionError,
    EncryptionError,
    KeyFingerprintMismatchError,
    MasterKeyNotFoundError,
    PrivateKeyNotFoundError,
    RecipientNotFoundError,
)

# --- Well-known names -------------------------------------------------------

KEY_FILE_NAME = ".dotseal.key"
ENV_VAR_NAME = "DOTSEAL_MASTER_KEY"

PRIVATE_KEY_FILE_NAME = ".dotseal.prv"
PRIVATE_ENV_VAR_NAME = "DOTSEAL_PRIVATE_KEY"

BANNER = "# Generated by dotseal. DO NOT EDIT VALUES MANUALLY."
METADATA_PREFIX = "# dotseal:"
METADATA_VERSION = "1"  # symmetric (single master key)
METADATA_VERSION_ASYM = "2"  # asymmetric (X25519 multi-recipient envelope)
PLAINTEXT_KEYS_TOKEN = "plain_keys"
PLAINTEXT_REGEX_TOKEN = "plain_re"

# A recipient slot lives in its own comment line, e.g.
#   # dotseal:recipient fp=<fp> ephem=<b64> enc=<b64>
RECIPIENT_PREFIX = f"{METADATA_PREFIX}recipient "

# The footer (version/algorithm) line always has a space after the colon,
# which is how we tell it apart from the recipient lines above.
_FOOTER_PREFIX = f"{METADATA_PREFIX} "


# --- Key resolution ---------------------------------------------------------

def find_key_file(start_dir: Optional[str] = None) -> Optional[str]:
    """Return the path to a local key file, searching upward from ``start_dir``.

    Walks up the directory tree (like git looking for ``.git``) so the tool
    works from subdirectories of a project.
    """
    current = os.path.abspath(start_dir or os.getcwd())
    while True:
        candidate = os.path.join(current, KEY_FILE_NAME)
        if os.path.isfile(candidate):
            return candidate
        parent = os.path.dirname(current)
        if parent == current:
            return None
        current = parent


def resolve_master_key(
    master_key: Optional[str] = None,
    *,
    key_file: Optional[str] = None,
    search_dir: Optional[str] = None,
) -> str:
    """Resolve the master key as a base64 string.

    Resolution order (first match wins):
        1. ``master_key`` argument,
        2. an explicit ``key_file`` path (an error if it does not exist),
        3. the ``DOTSEAL_MASTER_KEY`` environment variable,
        4. a discovered local key file.

    An explicitly requested ``key_file`` always wins over the ambient
    environment: a user who points at a specific key must never silently get a
    different one.

    Raises:
        MasterKeyNotFoundError: if no key can be found, or if an explicit
            ``key_file`` does not exist.
    """
    if master_key:
        return master_key.strip()

    if key_file:
        if not os.path.isfile(key_file):
            raise MasterKeyNotFoundError(f"Key file not found: {key_file}")
        with open(key_file, "r", encoding="utf-8") as fh:
            return fh.read().strip()

    env_value = os.environ.get(ENV_VAR_NAME)
    if env_value and env_value.strip():
        return env_value.strip()

    path = find_key_file(search_dir)
    if path and os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as fh:
            return fh.read().strip()

    raise MasterKeyNotFoundError(
        "No master key found. Provide one explicitly, set the "
        f"{ENV_VAR_NAME} environment variable, or run `dotseal init` "
        f"to create a local {KEY_FILE_NAME} file."
    )


def find_private_key_file(start_dir: Optional[str] = None) -> Optional[str]:
    """Return the path to a local recipient private key file, searching upward."""
    current = os.path.abspath(start_dir or os.getcwd())
    while True:
        candidate = os.path.join(current, PRIVATE_KEY_FILE_NAME)
        if os.path.isfile(candidate):
            return candidate
        parent = os.path.dirname(current)
        if parent == current:
            return None
        current = parent


def resolve_private_key(
    private_key: Optional[str] = None,
    *,
    key_file: Optional[str] = None,
    search_dir: Optional[str] = None,
) -> str:
    """Resolve a recipient private key (``dsk-prv-...``) string.

    Resolution order (first match wins):
        1. ``private_key`` argument,
        2. an explicit ``key_file`` path (an error if it does not exist),
        3. the ``DOTSEAL_PRIVATE_KEY`` environment variable,
        4. a discovered local key file.

    Raises:
        PrivateKeyNotFoundError: if no private key can be found, or if an
            explicit ``key_file`` does not exist.
    """
    if private_key:
        return private_key.strip()

    if key_file:
        if not os.path.isfile(key_file):
            raise PrivateKeyNotFoundError(f"Private key file not found: {key_file}")
        with open(key_file, "r", encoding="utf-8") as fh:
            return fh.read().strip()

    env_value = os.environ.get(PRIVATE_ENV_VAR_NAME)
    if env_value and env_value.strip():
        return env_value.strip()

    path = find_private_key_file(search_dir)
    if path and os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as fh:
            return fh.read().strip()

    raise PrivateKeyNotFoundError(
        "No recipient private key found. Provide one explicitly, set the "
        f"{PRIVATE_ENV_VAR_NAME} environment variable, or run `dotseal keygen` "
        f"to create a local {PRIVATE_KEY_FILE_NAME} file."
    )


# --- Metadata ---------------------------------------------------------------

def _encode_regex_token(regexes: List[str]) -> str:
    encoded = [
        base64.urlsafe_b64encode(pattern.encode("utf-8")).decode("ascii")
        for pattern in regexes
    ]
    return ",".join(encoded)


def _decode_regex_token(token: str) -> List[str]:
    patterns: List[str] = []
    for chunk in token.split(","):
        text = chunk.strip()
        if not text:
            continue
        try:
            decoded = base64.urlsafe_b64decode(text.encode("ascii")).decode("utf-8")
        except Exception as exc:  # pragma: no cover - defensive
            raise EncryptionError(
                "Invalid dotseal metadata: failed to decode plain-key regex policy."
            ) from exc
        patterns.append(decoded)
    return patterns


def _compile_regexes(regexes: List[str]) -> List[Pattern[str]]:
    compiled: List[Pattern[str]] = []
    for pattern in regexes:
        try:
            compiled.append(re.compile(pattern))
        except re.error as exc:
            raise EncryptionError(
                f"Invalid plain-key regex in policy: {pattern!r} ({exc})"
            ) from exc
    return compiled


def parse_plaintext_policy(meta: Dict[str, str]) -> Tuple[Set[str], List[str]]:
    keys_raw = meta.get(PLAINTEXT_KEYS_TOKEN, "").strip()
    regex_raw = meta.get(PLAINTEXT_REGEX_TOKEN, "").strip()
    keys = {name for name in keys_raw.split(",") if name}
    regexes = _decode_regex_token(regex_raw) if regex_raw else []
    return keys, regexes


def _metadata_policy_tokens(plain_keys: Set[str], plain_key_regex: List[str]) -> str:
    tokens: List[str] = []
    if plain_keys:
        tokens.append(
            f"{PLAINTEXT_KEYS_TOKEN}=" + ",".join(sorted(plain_keys))
        )
    if plain_key_regex:
        tokens.append(
            f"{PLAINTEXT_REGEX_TOKEN}=" + _encode_regex_token(plain_key_regex)
        )
    return (" " + " ".join(tokens)) if tokens else ""


def _resolved_plaintext_policy(
    parsed: parser.ParsedEnv,
    plain_keys: Optional[List[str]],
    plain_key_regex: Optional[List[str]],
) -> Tuple[Set[str], List[str], List[Pattern[str]]]:
    existing_keys, existing_regex = parse_plaintext_policy(parse_metadata(parsed))
    if plain_keys is None and plain_key_regex is None:
        resolved_keys, resolved_regex = existing_keys, existing_regex
    else:
        if plain_keys is None:
            resolved_keys = existing_keys
        else:
            resolved_keys = {name for name in plain_keys if name}
        if plain_key_regex is None:
            resolved_regex = existing_regex
        else:
            resolved_regex = [pattern for pattern in plain_key_regex if pattern]
    compiled = _compile_regexes(resolved_regex)
    return resolved_keys, resolved_regex, compiled


def keys_newly_sealed_by_policy_override(
    original: parser.ParsedEnv,
    cleartext: parser.ParsedEnv,
    *,
    plain_keys: Optional[List[str]] = None,
    plain_key_regex: Optional[List[str]] = None,
) -> List[str]:
    """Entry keys that were plaintext under the file policy but will be sealed under the override."""
    if plain_keys is None and plain_key_regex is None:
        return []
    old_keys, old_regex = parse_plaintext_policy(parse_metadata(original))
    old_compiled = _compile_regexes(old_regex)
    new_keys, new_regex, new_compiled = _resolved_plaintext_policy(
        original, plain_keys, plain_key_regex
    )
    newly_sealed: List[str] = []
    for record in cleartext.records:
        if record.kind != "entry":
            continue
        key = record.key
        was_plain = not _should_encrypt_value(key, old_keys, old_compiled)
        will_seal = _should_encrypt_value(key, new_keys, new_compiled)
        if was_plain and will_seal:
            newly_sealed.append(key)
    return sorted(newly_sealed)


def _should_encrypt_value(
    key: str, plain_keys: Set[str], plain_regex_compiled: List[Pattern[str]]
) -> bool:
    if key in plain_keys:
        return False
    return not any(pattern.fullmatch(key) for pattern in plain_regex_compiled)


def build_metadata_line(
    key_bytes: bytes,
    *,
    plain_keys: Optional[Set[str]] = None,
    plain_key_regex: Optional[List[str]] = None,
) -> str:
    fp = crypto.key_fingerprint(key_bytes)
    return (
        f"{METADATA_PREFIX} v={METADATA_VERSION} alg={crypto.ALGORITHM} key_fp={fp}"
        f"{_metadata_policy_tokens(plain_keys or set(), plain_key_regex or [])}"
    )


def build_metadata_line_asym(
    *,
    plain_keys: Optional[Set[str]] = None,
    plain_key_regex: Optional[List[str]] = None,
) -> str:
    return (
        f"{METADATA_PREFIX} v={METADATA_VERSION_ASYM} alg={crypto.ALGORITHM_ASYM}"
        f"{_metadata_policy_tokens(plain_keys or set(), plain_key_regex or [])}"
    )


def build_recipient_line(fingerprint: str, ephem: str, enc: str) -> str:
    return f"{RECIPIENT_PREFIX}fp={fingerprint} ephem={ephem} enc={enc}"


def _parse_tokens(body: str) -> Dict[str, str]:
    """Parse ``k=v`` whitespace-separated tokens; tokens without ``=`` are skipped."""
    fields: Dict[str, str] = {}
    for token in body.split():
        if "=" in token:
            k, v = token.split("=", 1)
            fields[k] = v
    return fields


def _is_footer_line(text: str) -> bool:
    """True if a stripped comment line is a real dotseal footer.

    Requires a ``v=`` token so that a user comment that merely *starts* with
    ``# dotseal: `` can neither shadow the real footer nor be mistaken for it
    (and silently deleted) -- see ``parse_metadata`` / ``_strip_managed_comments``.
    """
    if not text.startswith(_FOOTER_PREFIX):
        return False
    return "v" in _parse_tokens(text[len(METADATA_PREFIX):].strip())


def parse_metadata(parsed: parser.ParsedEnv) -> Dict[str, str]:
    """Extract the ``# dotseal:`` footer tokens (version/algorithm), if present."""
    for record in parsed.records:
        if record.kind != "comment":
            continue
        text = record.raw.strip()
        if text.startswith(RECIPIENT_PREFIX):
            continue  # recipient lines are parsed separately
        if _is_footer_line(text):
            return _parse_tokens(text[len(METADATA_PREFIX):].strip())
    return {}


def parse_recipients(parsed: parser.ParsedEnv) -> List[Dict[str, str]]:
    """Extract all ``# dotseal:recipient`` slots, in file order."""
    recipients: List[Dict[str, str]] = []
    for record in parsed.records:
        if record.kind != "comment":
            continue
        text = record.raw.strip()
        if not text.startswith(RECIPIENT_PREFIX):
            continue
        fields = _parse_tokens(text[len(RECIPIENT_PREFIX):].strip())
        if {"fp", "ephem", "enc"} <= fields.keys():
            recipients.append(
                {"fp": fields["fp"], "ephem": fields["ephem"], "enc": fields["enc"]}
            )
    return recipients


def _is_asymmetric(parsed: parser.ParsedEnv) -> bool:
    """True if the parsed file carries asymmetric metadata or recipient slots.

    Recipient slots count even when the footer is missing or damaged, so an
    asymmetric file never silently falls back to the symmetric code path.
    """
    return _is_asym_metadata(parse_metadata(parsed)) or bool(parse_recipients(parsed))


def file_mode(text: str) -> str:
    """Return ``"asymmetric"`` or ``"symmetric"`` for an encrypted file's text."""
    return "asymmetric" if _is_asymmetric(parser.parse(text)) else "symmetric"


def _strip_managed_comments(parsed: parser.ParsedEnv) -> None:
    """Remove dotseal's own banner / recipient / footer comments (keep user ones)."""
    kept = []
    for record in parsed.records:
        if record.kind == "comment":
            text = record.raw.strip()
            if (
                text == BANNER
                or text.startswith(RECIPIENT_PREFIX)
                or _is_footer_line(text)
            ):
                continue
        kept.append(record)
    parsed.records = kept


# --- Whole-file transforms --------------------------------------------------

def _has_encrypted_values(parsed: parser.ParsedEnv) -> bool:
    return any(
        r.kind == "entry" and crypto.is_encrypted_value(r.value)
        for r in parsed.records
    )


def _is_asym_metadata(meta: Dict[str, str]) -> bool:
    return (
        meta.get("alg") == crypto.ALGORITHM_ASYM
        or meta.get("v") == METADATA_VERSION_ASYM
    )


def encrypt_text(
    text: str,
    key_bytes: bytes,
    *,
    plain_keys: Optional[List[str]] = None,
    plain_key_regex: Optional[List[str]] = None,
) -> str:
    """Encrypt all cleartext values in ``text``; return ``.env.enc`` text.

    Re-encrypting an already (or partially) encrypted file is supported only
    when the file's recorded fingerprint matches ``key_bytes``: existing
    ``ENC[...]`` values are then left untouched (idempotent) and only new
    cleartext values are encrypted. Anything else would silently produce a
    file whose footer and ciphertexts disagree -- undecryptable by any key.
    """
    parsed = parser.parse(text)
    if _is_asymmetric(parsed):
        raise EncryptionError(
            "This file is encrypted in asymmetric (multi-recipient) mode. "
            "Re-encrypting it with a symmetric master key would make it "
            "undecryptable. Decrypt it first, or keep using --recipient."
        )
    if _has_encrypted_values(parsed):
        meta = parse_metadata(parsed)
        recorded = meta.get("key_fp")
        if recorded is None:
            raise EncryptionError(
                "The file contains ENC[...] values but no dotseal metadata, so "
                "the key they were encrypted with cannot be verified. If these "
                "are leftovers from an encrypted file, decrypt it first; if a "
                "plaintext value genuinely looks like an ENC[...] token, it "
                "cannot be stored verbatim."
            )
        if recorded != crypto.key_fingerprint(key_bytes):
            raise KeyFingerprintMismatchError(
                "The file's existing ENC[...] values were encrypted with a "
                f"different master key (fingerprint {recorded}). Re-encrypting "
                "with this key would make the file undecryptable by any key. "
                "Decrypt with the old key first, then encrypt with the new one."
            )
    resolved_plain_keys, resolved_plain_regex, resolved_plain_regex_compiled = (
        _resolved_plaintext_policy(parsed, plain_keys, plain_key_regex)
    )
    _strip_managed_comments(parsed)
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            continue  # idempotent: already encrypted
        if _should_encrypt_value(
            record.key, resolved_plain_keys, resolved_plain_regex_compiled
        ):
            record.value = crypto.encrypt_value(key_bytes, record.value, aad=record.key)
        else:
            record.value = parser.format_value(record.value)

    # Drop from plain_keys any key that ended up ENC[…] in the output.
    # A key that was already encrypted and was skipped by the idempotency guard
    # must not appear in the footer: if it did, the next `dotseal edit` would
    # inherit that policy and silently unseal it without an explicit --plain-key
    # from the user.  Keys in the policy that simply don't exist in this file
    # (forward-looking entries) are kept as-is.
    encrypted_in_output: Set[str] = {
        r.key
        for r in parsed.records
        if r.kind == "entry" and crypto.is_encrypted_value(r.value)
    }
    written_plain_keys = resolved_plain_keys - encrypted_in_output

    body = parser.serialize(parsed).rstrip("\n")
    parts = [BANNER]
    if body:
        parts.append(body)
    parts.append(
        build_metadata_line(
            key_bytes,
            plain_keys=written_plain_keys,
            plain_key_regex=resolved_plain_regex,
        )
    )
    return "\n".join(parts) + "\n"


def _original_tokens(
    parsed: parser.ParsedEnv, decrypt_one
) -> Dict[str, Tuple[str, str]]:
    """Map each encrypted entry to ``name -> (token, plaintext)`` for reuse.

    Entries that fail to decrypt are simply skipped (they will be re-encrypted
    fresh). With duplicate names the last occurrence wins.
    """
    tokens: Dict[str, Tuple[str, str]] = {}
    for record in parsed.records:
        if record.kind != "entry" or not crypto.is_encrypted_value(record.value):
            continue
        with contextlib.suppress(DecryptionError):
            plaintext = decrypt_one(record.value, record.key)
            tokens[record.key] = (record.value, plaintext)
    return tokens


def reencrypt_text(
    cleartext: str,
    key_bytes: bytes,
    original_text: str,
    *,
    plain_keys: Optional[List[str]] = None,
    plain_key_regex: Optional[List[str]] = None,
) -> str:
    """Re-encrypt edited cleartext, reusing unchanged ciphertexts.

    This powers ``dotseal edit`` for symmetric files: values whose plaintext
    did not change keep their original ``ENC[...]`` token, so the committed
    diff shows only the variables that actually changed.
    """
    original = parser.parse(original_text)
    if _is_asymmetric(original):
        raise EncryptionError(
            "The original file is encrypted in asymmetric (multi-recipient) "
            "mode; re-encrypting it with a symmetric master key would drop "
            "its recipients. Use reencrypt_text_asymmetric with a recipient "
            "private key instead."
        )
    verify_key(original, key_bytes)
    reusable = _original_tokens(
        original, lambda token, name: crypto.decrypt_value(key_bytes, token, aad=name)
    )

    resolved_plain_keys, resolved_plain_regex, resolved_plain_regex_compiled = (
        _resolved_plaintext_policy(original, plain_keys, plain_key_regex)
    )
    parsed = parser.parse(cleartext)
    _strip_managed_comments(parsed)
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            continue  # an ENC token the editor left in place: keep verbatim
        if not _should_encrypt_value(
            record.key, resolved_plain_keys, resolved_plain_regex_compiled
        ):
            record.value = parser.format_value(record.value)
            continue
        previous = reusable.get(record.key)
        if previous is not None and previous[1] == record.value:
            record.value = previous[0]
        else:
            record.value = crypto.encrypt_value(key_bytes, record.value, aad=record.key)

    body = parser.serialize(parsed).rstrip("\n")
    parts = [BANNER]
    if body:
        parts.append(body)
    parts.append(
        build_metadata_line(
            key_bytes,
            plain_keys=resolved_plain_keys,
            plain_key_regex=resolved_plain_regex,
        )
    )
    return "\n".join(parts) + "\n"


def verify_key(parsed: parser.ParsedEnv, key_bytes: bytes) -> None:
    """Raise if the file's recorded fingerprint does not match ``key_bytes``."""
    meta = parse_metadata(parsed)
    recorded = meta.get("key_fp")
    if recorded and recorded != crypto.key_fingerprint(key_bytes):
        raise KeyFingerprintMismatchError(
            "The master key does not match the key used to encrypt this file "
            f"(expected fingerprint {recorded}). Wrong key?"
        )


def _reject_asymmetric_for_master_key(parsed: parser.ParsedEnv) -> None:
    if _is_asymmetric(parsed):
        raise DecryptionError(
            "This file is encrypted in asymmetric (multi-recipient) mode; "
            "decrypt it with a recipient private key, not a master key."
        )


def decrypt_text(text: str, key_bytes: bytes) -> str:
    """Decrypt all encrypted values in ``text``; return cleartext ``.env`` text."""
    parsed = parser.parse(text)
    _reject_asymmetric_for_master_key(parsed)
    verify_key(parsed, key_bytes)
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            plaintext = crypto.decrypt_value(key_bytes, record.value, aad=record.key)
            record.value = parser.format_value(plaintext)
        else:
            record.value = parser.format_value(record.value)
    _strip_managed_comments(parsed)
    return parser.serialize(parsed)


def decrypt_to_dict(text: str, key_bytes: bytes) -> Dict[str, str]:
    """Decrypt ``text`` into a ``{name: value}`` mapping, in memory only."""
    parsed = parser.parse(text)
    _reject_asymmetric_for_master_key(parsed)
    verify_key(parsed, key_bytes)
    result: Dict[str, str] = {}
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            result[record.key] = crypto.decrypt_value(
                key_bytes, record.value, aad=record.key
            )
        else:
            result[record.key] = record.value
    return result


# --- Asymmetric (multi-recipient) transforms --------------------------------

def _assemble_asym(
    parsed: parser.ParsedEnv,
    recipients: List[Dict[str, str]],
    *,
    plain_keys: Optional[Set[str]] = None,
    plain_key_regex: Optional[List[str]] = None,
) -> str:
    """Render a parsed body + recipient slots into final ``.env.enc`` text.

    The parsed records are expected to already hold encrypted (or to-be-kept)
    values; dotseal's own banner/footer/recipient comments are rebuilt here.
    """
    _strip_managed_comments(parsed)
    body = parser.serialize(parsed).rstrip("\n")
    lines = [BANNER]
    if body:
        lines.append(body)
    for r in recipients:
        lines.append(build_recipient_line(r["fp"], r["ephem"], r["enc"]))
    lines.append(
        build_metadata_line_asym(
            plain_keys=plain_keys or set(),
            plain_key_regex=plain_key_regex or [],
        )
    )
    return "\n".join(lines) + "\n"


def encrypt_text_asymmetric(
    text: str,
    recipient_public_keys: List[str],
    *,
    plain_keys: Optional[List[str]] = None,
    plain_key_regex: Optional[List[str]] = None,
) -> str:
    """Encrypt a cleartext file for one or more recipients (envelope scheme).

    The input must be cleartext: every asymmetric encryption generates a fresh
    data key, so any pre-existing ``ENC[...]`` value (encrypted under some
    other key) would survive verbatim and become undecryptable. We refuse
    loudly instead.
    """
    if not recipient_public_keys:
        raise EncryptionError("At least one recipient public key is required.")

    parsed = parser.parse(text)
    if _has_encrypted_values(parsed):
        raise EncryptionError(
            "The file already contains ENC[...] values. Asymmetric encryption "
            "always generates a fresh data key, so existing ciphertexts would "
            "become undecryptable. Decrypt the file first (or use `dotseal "
            "edit` / add-recipient to modify an existing asymmetric file)."
        )

    # De-duplicate by fingerprint while preserving order.
    seen = set()
    pubs: List[str] = []
    for pub in recipient_public_keys:
        fp = crypto.recipient_fingerprint(pub)
        if fp not in seen:
            seen.add(fp)
            pubs.append(pub)

    resolved_plain_keys, resolved_plain_regex, resolved_plain_regex_compiled = (
        _resolved_plaintext_policy(parsed, plain_keys, plain_key_regex)
    )
    _strip_managed_comments(parsed)
    dek = crypto.generate_data_key()
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if _should_encrypt_value(
            record.key, resolved_plain_keys, resolved_plain_regex_compiled
        ):
            record.value = crypto.encrypt_value(dek, record.value, aad=record.key)
        else:
            record.value = parser.format_value(record.value)

    encrypted_in_output: Set[str] = {
        r.key
        for r in parsed.records
        if r.kind == "entry" and crypto.is_encrypted_value(r.value)
    }
    written_plain_keys = resolved_plain_keys - encrypted_in_output

    recipients = []
    for pub in pubs:
        ephem, enc = crypto.wrap_dek(crypto.load_recipient_public_key(pub), dek)
        recipients.append(
            {"fp": crypto.recipient_fingerprint(pub), "ephem": ephem, "enc": enc}
        )
    return _assemble_asym(
        parsed,
        recipients,
        plain_keys=written_plain_keys,
        plain_key_regex=resolved_plain_regex,
    )


def recover_data_key(parsed: parser.ParsedEnv, private_key: str) -> bytes:
    """Recover the DEK from whichever recipient slot the private key can unwrap."""
    recipients = parse_recipients(parsed)
    if not recipients:
        raise DecryptionError(
            "No recipient slots found. This file is not asymmetric or is corrupt."
        )
    priv = crypto.load_recipient_private_key(private_key)
    my_fp = crypto.recipient_fingerprint(
        crypto.public_key_str_from_private(private_key)
    )
    # Try the slot matching our fingerprint first, then fall back to the rest.
    ordered = [r for r in recipients if r["fp"] == my_fp]
    ordered += [r for r in recipients if r["fp"] != my_fp]
    for r in ordered:
        try:
            return crypto.unwrap_dek(priv, r["ephem"], r["enc"])
        except DecryptionError:
            continue
    raise RecipientNotFoundError(
        "This private key is not a recipient of this file."
    )


def decrypt_text_asymmetric(text: str, private_key: str) -> str:
    """Decrypt an asymmetric file's values back to cleartext ``.env`` text."""
    parsed = parser.parse(text)
    dek = recover_data_key(parsed, private_key)
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            plaintext = crypto.decrypt_value(dek, record.value, aad=record.key)
            record.value = parser.format_value(plaintext)
        else:
            record.value = parser.format_value(record.value)
    _strip_managed_comments(parsed)
    return parser.serialize(parsed)


def decrypt_to_dict_asymmetric(text: str, private_key: str) -> Dict[str, str]:
    """Decrypt an asymmetric file into a ``{name: value}`` mapping, in memory."""
    parsed = parser.parse(text)
    dek = recover_data_key(parsed, private_key)
    result: Dict[str, str] = {}
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            result[record.key] = crypto.decrypt_value(dek, record.value, aad=record.key)
        else:
            result[record.key] = record.value
    return result


def reencrypt_text_asymmetric(
    cleartext: str,
    private_key: str,
    original_text: str,
    *,
    plain_keys: Optional[List[str]] = None,
    plain_key_regex: Optional[List[str]] = None,
) -> str:
    """Re-encrypt edited cleartext, reusing the original file's DEK and recipients.

    This is what powers ``dotseal edit`` for asymmetric files: it keeps the same
    data key and recipient slots, so editing never needs the recipients' public
    keys, only the editor's own private key. Values whose plaintext did not
    change keep their original ``ENC[...]`` token, so the committed diff shows
    only the variables that actually changed.
    """
    original = parser.parse(original_text)
    dek = recover_data_key(original, private_key)
    recipients = parse_recipients(original)
    reusable = _original_tokens(
        original, lambda token, name: crypto.decrypt_value(dek, token, aad=name)
    )

    resolved_plain_keys, resolved_plain_regex, resolved_plain_regex_compiled = (
        _resolved_plaintext_policy(original, plain_keys, plain_key_regex)
    )
    parsed = parser.parse(cleartext)
    _strip_managed_comments(parsed)
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            continue
        if not _should_encrypt_value(
            record.key, resolved_plain_keys, resolved_plain_regex_compiled
        ):
            record.value = parser.format_value(record.value)
            continue
        previous = reusable.get(record.key)
        if previous is not None and previous[1] == record.value:
            record.value = previous[0]
        else:
            record.value = crypto.encrypt_value(dek, record.value, aad=record.key)
    return _assemble_asym(
        parsed,
        recipients,
        plain_keys=resolved_plain_keys,
        plain_key_regex=resolved_plain_regex,
    )


def add_recipient_to_text(text: str, private_key: str, new_public_key: str) -> str:
    """Add a recipient to an existing asymmetric file (no value re-encryption).

    Requires a private key that is already a recipient, used to unwrap the DEK so
    it can be re-wrapped for the new recipient.
    """
    parsed = parser.parse(text)
    dek = recover_data_key(parsed, private_key)
    recipients = parse_recipients(parsed)
    new_fp = crypto.recipient_fingerprint(new_public_key)
    if not any(r["fp"] == new_fp for r in recipients):
        ephem, enc = crypto.wrap_dek(
            crypto.load_recipient_public_key(new_public_key), dek
        )
        recipients.append({"fp": new_fp, "ephem": ephem, "enc": enc})
    plain_keys, plain_key_regex = parse_plaintext_policy(parse_metadata(parsed))
    return _assemble_asym(
        parsed,
        recipients,
        plain_keys=plain_keys,
        plain_key_regex=plain_key_regex,
    )


def remove_recipient_from_text(text: str, identifier: str) -> str:
    """Remove a recipient slot by public key or fingerprint.

    Note: this does not rotate the data key, so a removed recipient can still
    decrypt older committed versions of the file. Rotate by re-encrypting from
    cleartext if you need to fully revoke access.
    """
    parsed = parser.parse(text)
    if identifier.strip().startswith(crypto.PUBKEY_PREFIX):
        target_fp = crypto.recipient_fingerprint(identifier)
    else:
        target_fp = identifier.strip()

    recipients = parse_recipients(parsed)
    remaining = [r for r in recipients if r["fp"] != target_fp]
    if len(remaining) == len(recipients):
        raise RecipientNotFoundError(
            f"No recipient with fingerprint {target_fp!r} found in this file."
        )
    if not remaining:
        raise EncryptionError(
            "Refusing to remove the last recipient (the file would be undecryptable)."
        )
    plain_keys, plain_key_regex = parse_plaintext_policy(parse_metadata(parsed))
    return _assemble_asym(
        parsed,
        remaining,
        plain_keys=plain_keys,
        plain_key_regex=plain_key_regex,
    )


# --- Filesystem helpers -----------------------------------------------------

def write_secret_file(path: str, text: str, *, mode: int = 0o600) -> None:
    """Write ``text`` to ``path`` with restrictive (owner-only) permissions.

    The content is written to a fresh ``O_EXCL`` temp file in the target
    directory and atomically renamed into place, so:

    * the secret is never readable through a pre-existing file's looser
      permissions (the temp file is born with ``mode``),
    * a crash mid-write cannot leave a truncated/corrupt target, and
    * a symlink planted at ``path`` is replaced rather than followed.
    """
    abs_path = os.path.abspath(path)
    directory = os.path.dirname(abs_path)
    fd, tmp_path = tempfile.mkstemp(prefix=".dotseal-tmp-", dir=directory)
    try:
        os.fchmod(fd, mode)
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp_path, abs_path)
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise
