"""High-level orchestration: key resolution and whole-file transforms.

This ties together :mod:`dotseal.crypto` (primitives) and
:mod:`dotseal.parser` (structure) into the operations the CLI and the
runtime loader actually need:

* find the master key (explicit arg -> env var -> local key file),
* encrypt / decrypt an entire file's text while preserving structure,
* embed and verify a key fingerprint so a wrong key fails fast.
"""

from __future__ import annotations

import os
from typing import Dict, List, Optional

from . import crypto, parser
from .exceptions import (
    DecryptionError,
    EncryptionError,
    KeyFingerprintMismatchError,
    MasterKeyNotFoundError,
    PrivateKeyNotFoundError,
    RecipientNotFoundError,
)

# --- Well-known names -------------------------------------------------------

KEY_FILE_NAME = ".dotseal.key"
ENV_VAR_NAME = "DOTSEAL_MASTER_KEY"

PRIVATE_KEY_FILE_NAME = ".dotseal.prv"
PRIVATE_ENV_VAR_NAME = "DOTSEAL_PRIVATE_KEY"

BANNER = "# Generated by dotseal. DO NOT EDIT VALUES MANUALLY."
METADATA_PREFIX = "# dotseal:"
METADATA_VERSION = "1"  # symmetric (single master key)
METADATA_VERSION_ASYM = "2"  # asymmetric (X25519 multi-recipient envelope)

# A recipient slot lives in its own comment line, e.g.
#   # dotseal:recipient fp=<fp> ephem=<b64> enc=<b64>
RECIPIENT_PREFIX = f"{METADATA_PREFIX}recipient "

# The footer (version/algorithm) line always has a space after the colon,
# which is how we tell it apart from the recipient lines above.
_FOOTER_PREFIX = f"{METADATA_PREFIX} "


# --- Key resolution ---------------------------------------------------------

def find_key_file(start_dir: Optional[str] = None) -> Optional[str]:
    """Return the path to a local key file, searching upward from ``start_dir``.

    Walks up the directory tree (like git looking for ``.git``) so the tool
    works from subdirectories of a project.
    """
    current = os.path.abspath(start_dir or os.getcwd())
    while True:
        candidate = os.path.join(current, KEY_FILE_NAME)
        if os.path.isfile(candidate):
            return candidate
        parent = os.path.dirname(current)
        if parent == current:
            return None
        current = parent


def resolve_master_key(
    master_key: Optional[str] = None,
    *,
    key_file: Optional[str] = None,
    search_dir: Optional[str] = None,
) -> str:
    """Resolve the master key as a base64 string.

    Resolution order (first match wins):
        1. ``master_key`` argument,
        2. the ``DOTSEAL_MASTER_KEY`` environment variable,
        3. an explicit ``key_file`` path, then a discovered local key file.

    Raises:
        MasterKeyNotFoundError: if no key can be found.
    """
    if master_key:
        return master_key.strip()

    env_value = os.environ.get(ENV_VAR_NAME)
    if env_value and env_value.strip():
        return env_value.strip()

    path = key_file or find_key_file(search_dir)
    if path and os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as fh:
            return fh.read().strip()

    raise MasterKeyNotFoundError(
        "No master key found. Provide one explicitly, set the "
        f"{ENV_VAR_NAME} environment variable, or run `dotseal init` "
        f"to create a local {KEY_FILE_NAME} file."
    )


def find_private_key_file(start_dir: Optional[str] = None) -> Optional[str]:
    """Return the path to a local recipient private key file, searching upward."""
    current = os.path.abspath(start_dir or os.getcwd())
    while True:
        candidate = os.path.join(current, PRIVATE_KEY_FILE_NAME)
        if os.path.isfile(candidate):
            return candidate
        parent = os.path.dirname(current)
        if parent == current:
            return None
        current = parent


def resolve_private_key(
    private_key: Optional[str] = None,
    *,
    key_file: Optional[str] = None,
    search_dir: Optional[str] = None,
) -> str:
    """Resolve a recipient private key (``dsk-prv-...``) string.

    Resolution order (first match wins):
        1. ``private_key`` argument,
        2. the ``DOTSEAL_PRIVATE_KEY`` environment variable,
        3. an explicit ``key_file`` path, then a discovered local key file.

    Raises:
        PrivateKeyNotFoundError: if no private key can be found.
    """
    if private_key:
        return private_key.strip()

    env_value = os.environ.get(PRIVATE_ENV_VAR_NAME)
    if env_value and env_value.strip():
        return env_value.strip()

    path = key_file or find_private_key_file(search_dir)
    if path and os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as fh:
            return fh.read().strip()

    raise PrivateKeyNotFoundError(
        "No recipient private key found. Provide one explicitly, set the "
        f"{PRIVATE_ENV_VAR_NAME} environment variable, or run `dotseal keygen` "
        f"to create a local {PRIVATE_KEY_FILE_NAME} file."
    )


# --- Metadata ---------------------------------------------------------------

def build_metadata_line(key_bytes: bytes) -> str:
    fp = crypto.key_fingerprint(key_bytes)
    return f"{METADATA_PREFIX} v={METADATA_VERSION} alg={crypto.ALGORITHM} key_fp={fp}"


def build_metadata_line_asym() -> str:
    return f"{METADATA_PREFIX} v={METADATA_VERSION_ASYM} alg={crypto.ALGORITHM_ASYM}"


def build_recipient_line(fingerprint: str, ephem: str, enc: str) -> str:
    return f"{RECIPIENT_PREFIX}fp={fingerprint} ephem={ephem} enc={enc}"


def parse_metadata(parsed: parser.ParsedEnv) -> Dict[str, str]:
    """Extract the ``# dotseal:`` footer tokens (version/algorithm), if present."""
    for record in parsed.records:
        if record.kind != "comment":
            continue
        text = record.raw.strip()
        if text.startswith(RECIPIENT_PREFIX):
            continue  # recipient lines are parsed separately
        if text.startswith(_FOOTER_PREFIX):
            body = text[len(METADATA_PREFIX):].strip()
            meta: Dict[str, str] = {}
            for token in body.split():
                if "=" in token:
                    k, v = token.split("=", 1)
                    meta[k] = v
            return meta
    return {}


def parse_recipients(parsed: parser.ParsedEnv) -> List[Dict[str, str]]:
    """Extract all ``# dotseal:recipient`` slots, in file order."""
    recipients: List[Dict[str, str]] = []
    for record in parsed.records:
        if record.kind != "comment":
            continue
        text = record.raw.strip()
        if not text.startswith(RECIPIENT_PREFIX):
            continue
        body = text[len(RECIPIENT_PREFIX):].strip()
        fields: Dict[str, str] = {}
        for token in body.split():
            if "=" in token:
                k, v = token.split("=", 1)
                fields[k] = v
        if {"fp", "ephem", "enc"} <= fields.keys():
            recipients.append(
                {"fp": fields["fp"], "ephem": fields["ephem"], "enc": fields["enc"]}
            )
    return recipients


def file_mode(text: str) -> str:
    """Return ``"asymmetric"`` or ``"symmetric"`` for an encrypted file's text."""
    meta = parse_metadata(parser.parse(text))
    if meta.get("alg") == crypto.ALGORITHM_ASYM or meta.get("v") == METADATA_VERSION_ASYM:
        return "asymmetric"
    return "symmetric"


def _strip_managed_comments(parsed: parser.ParsedEnv) -> None:
    """Remove dotseal's own banner / metadata comments (keep user ones)."""
    kept = []
    for record in parsed.records:
        if record.kind == "comment":
            text = record.raw.strip()
            if text == BANNER or text.startswith(METADATA_PREFIX):
                continue
        kept.append(record)
    parsed.records = kept


# --- Whole-file transforms --------------------------------------------------

def encrypt_text(text: str, key_bytes: bytes) -> str:
    """Encrypt all cleartext values in ``text``; return ``.env.enc`` text."""
    parsed = parser.parse(text)
    _strip_managed_comments(parsed)
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            continue  # idempotent: already encrypted
        record.value = crypto.encrypt_value(key_bytes, record.value, aad=record.key)

    body = parser.serialize(parsed).rstrip("\n")
    parts = [BANNER]
    if body:
        parts.append(body)
    parts.append(build_metadata_line(key_bytes))
    return "\n".join(parts) + "\n"


def verify_key(parsed: parser.ParsedEnv, key_bytes: bytes) -> None:
    """Raise if the file's recorded fingerprint does not match ``key_bytes``."""
    meta = parse_metadata(parsed)
    recorded = meta.get("key_fp")
    if recorded and recorded != crypto.key_fingerprint(key_bytes):
        raise KeyFingerprintMismatchError(
            "The master key does not match the key used to encrypt this file "
            f"(expected fingerprint {recorded}). Wrong key?"
        )


def decrypt_text(text: str, key_bytes: bytes) -> str:
    """Decrypt all encrypted values in ``text``; return cleartext ``.env`` text."""
    parsed = parser.parse(text)
    verify_key(parsed, key_bytes)
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            plaintext = crypto.decrypt_value(key_bytes, record.value, aad=record.key)
            record.value = parser.format_value(plaintext)
        else:
            record.value = parser.format_value(record.value)
    _strip_managed_comments(parsed)
    return parser.serialize(parsed)


def decrypt_to_dict(text: str, key_bytes: bytes) -> Dict[str, str]:
    """Decrypt ``text`` into a ``{name: value}`` mapping, in memory only."""
    parsed = parser.parse(text)
    verify_key(parsed, key_bytes)
    result: Dict[str, str] = {}
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            result[record.key] = crypto.decrypt_value(
                key_bytes, record.value, aad=record.key
            )
        else:
            result[record.key] = record.value
    return result


# --- Asymmetric (multi-recipient) transforms --------------------------------

def _assemble_asym(
    parsed: parser.ParsedEnv, recipients: List[Dict[str, str]]
) -> str:
    """Render a parsed body + recipient slots into final ``.env.enc`` text.

    The parsed records are expected to already hold encrypted (or to-be-kept)
    values; dotseal's own banner/footer/recipient comments are rebuilt here.
    """
    _strip_managed_comments(parsed)
    body = parser.serialize(parsed).rstrip("\n")
    lines = [BANNER]
    if body:
        lines.append(body)
    for r in recipients:
        lines.append(build_recipient_line(r["fp"], r["ephem"], r["enc"]))
    lines.append(build_metadata_line_asym())
    return "\n".join(lines) + "\n"


def encrypt_text_asymmetric(text: str, recipient_public_keys: List[str]) -> str:
    """Encrypt a cleartext file for one or more recipients (envelope scheme)."""
    if not recipient_public_keys:
        raise EncryptionError("At least one recipient public key is required.")

    # De-duplicate by fingerprint while preserving order.
    seen = set()
    pubs: List[str] = []
    for pub in recipient_public_keys:
        fp = crypto.recipient_fingerprint(pub)
        if fp not in seen:
            seen.add(fp)
            pubs.append(pub)

    parsed = parser.parse(text)
    _strip_managed_comments(parsed)
    dek = crypto.generate_data_key()
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            continue  # idempotent: already encrypted
        record.value = crypto.encrypt_value(dek, record.value, aad=record.key)

    recipients = []
    for pub in pubs:
        ephem, enc = crypto.wrap_dek(crypto.load_recipient_public_key(pub), dek)
        recipients.append(
            {"fp": crypto.recipient_fingerprint(pub), "ephem": ephem, "enc": enc}
        )
    return _assemble_asym(parsed, recipients)


def recover_data_key(parsed: parser.ParsedEnv, private_key: str) -> bytes:
    """Recover the DEK from whichever recipient slot the private key can unwrap."""
    recipients = parse_recipients(parsed)
    if not recipients:
        raise DecryptionError(
            "No recipient slots found. This file is not asymmetric or is corrupt."
        )
    priv = crypto.load_recipient_private_key(private_key)
    my_fp = crypto.recipient_fingerprint(
        crypto.public_key_str_from_private(private_key)
    )
    # Try the slot matching our fingerprint first, then fall back to the rest.
    ordered = [r for r in recipients if r["fp"] == my_fp]
    ordered += [r for r in recipients if r["fp"] != my_fp]
    for r in ordered:
        try:
            return crypto.unwrap_dek(priv, r["ephem"], r["enc"])
        except DecryptionError:
            continue
    raise RecipientNotFoundError(
        "This private key is not a recipient of this file."
    )


def decrypt_text_asymmetric(text: str, private_key: str) -> str:
    """Decrypt an asymmetric file's values back to cleartext ``.env`` text."""
    parsed = parser.parse(text)
    dek = recover_data_key(parsed, private_key)
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            plaintext = crypto.decrypt_value(dek, record.value, aad=record.key)
            record.value = parser.format_value(plaintext)
        else:
            record.value = parser.format_value(record.value)
    _strip_managed_comments(parsed)
    return parser.serialize(parsed)


def decrypt_to_dict_asymmetric(text: str, private_key: str) -> Dict[str, str]:
    """Decrypt an asymmetric file into a ``{name: value}`` mapping, in memory."""
    parsed = parser.parse(text)
    dek = recover_data_key(parsed, private_key)
    result: Dict[str, str] = {}
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            result[record.key] = crypto.decrypt_value(dek, record.value, aad=record.key)
        else:
            result[record.key] = record.value
    return result


def reencrypt_text_asymmetric(
    cleartext: str, private_key: str, original_text: str
) -> str:
    """Re-encrypt edited cleartext, reusing the original file's DEK and recipients.

    This is what powers ``dotseal edit`` for asymmetric files: it keeps the same
    data key and recipient slots, so editing never needs the recipients' public
    keys, only the editor's own private key.
    """
    original = parser.parse(original_text)
    dek = recover_data_key(original, private_key)
    recipients = parse_recipients(original)

    parsed = parser.parse(cleartext)
    _strip_managed_comments(parsed)
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            continue
        record.value = crypto.encrypt_value(dek, record.value, aad=record.key)
    return _assemble_asym(parsed, recipients)


def add_recipient_to_text(text: str, private_key: str, new_public_key: str) -> str:
    """Add a recipient to an existing asymmetric file (no value re-encryption).

    Requires a private key that is already a recipient, used to unwrap the DEK so
    it can be re-wrapped for the new recipient.
    """
    parsed = parser.parse(text)
    dek = recover_data_key(parsed, private_key)
    recipients = parse_recipients(parsed)
    new_fp = crypto.recipient_fingerprint(new_public_key)
    if not any(r["fp"] == new_fp for r in recipients):
        ephem, enc = crypto.wrap_dek(
            crypto.load_recipient_public_key(new_public_key), dek
        )
        recipients.append({"fp": new_fp, "ephem": ephem, "enc": enc})
    return _assemble_asym(parsed, recipients)


def remove_recipient_from_text(text: str, identifier: str) -> str:
    """Remove a recipient slot by public key or fingerprint.

    Note: this does not rotate the data key, so a removed recipient can still
    decrypt older committed versions of the file. Rotate by re-encrypting from
    cleartext if you need to fully revoke access.
    """
    parsed = parser.parse(text)
    if identifier.strip().startswith(crypto.PUBKEY_PREFIX):
        target_fp = crypto.recipient_fingerprint(identifier)
    else:
        target_fp = identifier.strip()

    recipients = parse_recipients(parsed)
    remaining = [r for r in recipients if r["fp"] != target_fp]
    if len(remaining) == len(recipients):
        raise RecipientNotFoundError(
            f"No recipient with fingerprint {target_fp!r} found in this file."
        )
    if not remaining:
        raise EncryptionError(
            "Refusing to remove the last recipient (the file would be undecryptable)."
        )
    return _assemble_asym(parsed, remaining)


# --- Filesystem helpers -----------------------------------------------------

def write_secret_file(path: str, text: str, *, mode: int = 0o600) -> None:
    """Write ``text`` to ``path`` with restrictive (owner-only) permissions."""
    directory = os.path.dirname(os.path.abspath(path))
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
    finally:
        # Re-assert mode in case the file pre-existed with looser perms.
        try:
            os.chmod(path, mode)
        except OSError:
            pass
    _ = directory  # reserved for future atomic-rename hardening
