import {
  ALGORITHM,
  decryptValue,
  encryptValue,
  isEncryptedValue,
  keyFingerprint
} from "./crypto";
import { KeyFingerprintMismatchError } from "./errors";
import { formatValue, parse, ParsedEnv, serialize } from "./parser";

export const KEY_FILE_NAME = ".dotseal.key";
export const ENV_VAR_NAME = "DOTSEAL_MASTER_KEY";
export const BANNER = "# Generated by dotseal. DO NOT EDIT VALUES MANUALLY.";
export const METADATA_PREFIX = "# dotseal:";
export const METADATA_VERSION = "1";

export function buildMetadataLine(keyBytes: Buffer): string {
  return `${METADATA_PREFIX} v=${METADATA_VERSION} alg=${ALGORITHM} key_fp=${keyFingerprint(keyBytes)}`;
}

export function parseMetadata(parsed: ParsedEnv): Map<string, string> {
  for (const record of parsed.records) {
    if (record.kind === "comment" && record.raw.trim().startsWith(METADATA_PREFIX)) {
      const body = record.raw.trim().slice(METADATA_PREFIX.length).trim();
      const meta = new Map<string, string>();
      for (const token of body.split(/\s+/)) {
        const index = token.indexOf("=");
        if (index !== -1) {
          meta.set(token.slice(0, index), token.slice(index + 1));
        }
      }
      return meta;
    }
  }
  return new Map();
}

function stripManagedComments(parsed: ParsedEnv): void {
  parsed.records = parsed.records.filter((record) => {
    if (record.kind !== "comment") {
      return true;
    }
    const text = record.raw.trim();
    return text !== BANNER && !text.startsWith(METADATA_PREFIX);
  });
}

export function encryptText(text: string, keyBytes: Buffer): string {
  const parsed = parse(text);
  stripManagedComments(parsed);
  for (const record of parsed.records) {
    if (record.kind !== "entry") {
      continue;
    }
    if (isEncryptedValue(record.value)) {
      continue;
    }
    record.value = encryptValue(keyBytes, record.value, record.key);
  }

  const body = serialize(parsed).replace(/\n+$/, "");
  const parts = [BANNER];
  if (body.length > 0) {
    parts.push(body);
  }
  parts.push(buildMetadataLine(keyBytes));
  return `${parts.join("\n")}\n`;
}

export function verifyKey(parsed: ParsedEnv, keyBytes: Buffer): void {
  const recorded = parseMetadata(parsed).get("key_fp");
  const actual = keyFingerprint(keyBytes);
  if (recorded !== undefined && recorded !== actual) {
    throw new KeyFingerprintMismatchError(
      `The master key does not match the key used to encrypt this file (expected fingerprint ${recorded}). Wrong key?`
    );
  }
}

export function decryptText(text: string, keyBytes: Buffer): string {
  const parsed = parse(text);
  verifyKey(parsed, keyBytes);
  for (const record of parsed.records) {
    if (record.kind !== "entry") {
      continue;
    }
    if (isEncryptedValue(record.value)) {
      const plaintext = decryptValue(keyBytes, record.value, record.key);
      record.value = formatValue(plaintext);
    } else {
      record.value = formatValue(record.value);
    }
  }
  stripManagedComments(parsed);
  return serialize(parsed);
}

export function decryptToObject(text: string, keyBytes: Buffer): Record<string, string> {
  const parsed = parse(text);
  verifyKey(parsed, keyBytes);
  const result: Record<string, string> = {};
  for (const record of parsed.records) {
    if (record.kind !== "entry") {
      continue;
    }
    result[record.key] = isEncryptedValue(record.value)
      ? decryptValue(keyBytes, record.value, record.key)
      : record.value;
  }
  return result;
}
