import {
  ALGORITHM,
  decryptValue,
  encryptValue,
  isEncryptedValue,
  keyFingerprint
} from "./crypto";
import {
  DecryptionError,
  DotsealError,
  EncryptionError,
  KeyFingerprintMismatchError
} from "./errors";
import { formatValue, parse, ParsedEnv, serialize } from "./parser";

export const KEY_FILE_NAME = ".dotseal.key";
export const ENV_VAR_NAME = "DOTSEAL_MASTER_KEY";
export const BANNER = "# Generated by dotseal. DO NOT EDIT VALUES MANUALLY.";
export const METADATA_PREFIX = "# dotseal:";
export const METADATA_VERSION = "1";
export const ALGORITHM_ASYM = "AES_GCM+X25519";
export const METADATA_VERSION_ASYM = "2";

// Recipient slots live in their own comment lines; the footer always has a
// space after the colon, which is how the two are told apart (mirrors the
// Python implementation).
const RECIPIENT_PREFIX = `${METADATA_PREFIX}recipient `;
const FOOTER_PREFIX = `${METADATA_PREFIX} `;

export function buildMetadataLine(keyBytes: Buffer): string {
  return `${METADATA_PREFIX} v=${METADATA_VERSION} alg=${ALGORITHM} key_fp=${keyFingerprint(keyBytes)}`;
}

function parseTokens(body: string): Map<string, string> {
  const fields = new Map<string, string>();
  for (const token of body.split(/\s+/)) {
    const index = token.indexOf("=");
    if (index !== -1) {
      fields.set(token.slice(0, index), token.slice(index + 1));
    }
  }
  return fields;
}

/**
 * True if a stripped comment line is a real dotseal footer. Requires a `v=`
 * token so a user comment that merely starts with `# dotseal: ` can neither
 * shadow the real footer nor be mistaken for it (and silently deleted).
 */
function isFooterLine(text: string): boolean {
  if (!text.startsWith(FOOTER_PREFIX)) {
    return false;
  }
  return parseTokens(text.slice(METADATA_PREFIX.length).trim()).has("v");
}

export function parseMetadata(parsed: ParsedEnv): Map<string, string> {
  for (const record of parsed.records) {
    if (record.kind !== "comment") {
      continue;
    }
    const text = record.raw.trim();
    if (text.startsWith(RECIPIENT_PREFIX)) {
      continue; // recipient slots are not the version/algorithm footer
    }
    if (isFooterLine(text)) {
      return parseTokens(text.slice(METADATA_PREFIX.length).trim());
    }
  }
  return new Map();
}

function isAsymmetric(parsed: ParsedEnv): boolean {
  const meta = parseMetadata(parsed);
  return (
    meta.get("alg") === ALGORITHM_ASYM ||
    meta.get("v") === METADATA_VERSION_ASYM ||
    parsed.records.some(
      (record) =>
        record.kind === "comment" && record.raw.trim().startsWith(RECIPIENT_PREFIX)
    )
  );
}

function assertNotAsymmetric(parsed: ParsedEnv): void {
  if (isAsymmetric(parsed)) {
    throw new DotsealError(
      "This file is encrypted in asymmetric (multi-recipient) mode, which the " +
        "VS Code extension does not support yet. Use the dotseal CLI (`dotseal edit`)."
    );
  }
}

function hasEncryptedValues(parsed: ParsedEnv): boolean {
  return parsed.records.some(
    (record) => record.kind === "entry" && isEncryptedValue(record.value)
  );
}

function stripManagedComments(parsed: ParsedEnv): void {
  parsed.records = parsed.records.filter((record) => {
    if (record.kind !== "comment") {
      return true;
    }
    const text = record.raw.trim();
    return (
      text !== BANNER && !text.startsWith(RECIPIENT_PREFIX) && !isFooterLine(text)
    );
  });
}

export function encryptText(text: string, keyBytes: Buffer): string {
  const parsed = parse(text);
  assertNotAsymmetric(parsed);
  if (hasEncryptedValues(parsed)) {
    const recorded = parseMetadata(parsed).get("key_fp");
    if (recorded === undefined) {
      throw new EncryptionError(
        "The file contains ENC[...] values but no dotseal metadata, so the key " +
          "they were encrypted with cannot be verified. Decrypt it first."
      );
    }
    // Refuse to mix ciphertexts from two different keys in one file -- the
    // result would be undecryptable by either key.
    verifyKey(parsed, keyBytes);
  }
  stripManagedComments(parsed);
  for (const record of parsed.records) {
    if (record.kind !== "entry") {
      continue;
    }
    if (isEncryptedValue(record.value)) {
      continue;
    }
    record.value = encryptValue(keyBytes, record.value, record.key);
  }

  const body = serialize(parsed).replace(/\n+$/, "");
  const parts = [BANNER];
  if (body.length > 0) {
    parts.push(body);
  }
  parts.push(buildMetadataLine(keyBytes));
  return `${parts.join("\n")}\n`;
}

/**
 * Re-encrypt edited cleartext, reusing the original ciphertext for every
 * value whose plaintext did not change. This keeps saves diff-friendly: only
 * variables that actually changed get a fresh nonce/ciphertext.
 */
export function reencryptText(
  cleartext: string,
  keyBytes: Buffer,
  originalText: string
): string {
  const original = parse(originalText);
  assertNotAsymmetric(original);
  verifyKey(original, keyBytes);

  const reusable = new Map<string, { token: string; plaintext: string }>();
  for (const record of original.records) {
    if (record.kind !== "entry" || !isEncryptedValue(record.value)) {
      continue;
    }
    try {
      reusable.set(record.key, {
        token: record.value,
        plaintext: decryptValue(keyBytes, record.value, record.key)
      });
    } catch (error) {
      if (!(error instanceof DecryptionError)) {
        throw error;
      }
      // Undecryptable entries are simply re-encrypted fresh.
    }
  }

  const parsed = parse(cleartext);
  stripManagedComments(parsed);
  for (const record of parsed.records) {
    if (record.kind !== "entry" || isEncryptedValue(record.value)) {
      continue;
    }
    const previous = reusable.get(record.key);
    record.value =
      previous !== undefined && previous.plaintext === record.value
        ? previous.token
        : encryptValue(keyBytes, record.value, record.key);
  }

  const body = serialize(parsed).replace(/\n+$/, "");
  const parts = [BANNER];
  if (body.length > 0) {
    parts.push(body);
  }
  parts.push(buildMetadataLine(keyBytes));
  return `${parts.join("\n")}\n`;
}

export function verifyKey(parsed: ParsedEnv, keyBytes: Buffer): void {
  const recorded = parseMetadata(parsed).get("key_fp");
  const actual = keyFingerprint(keyBytes);
  if (recorded !== undefined && recorded !== actual) {
    throw new KeyFingerprintMismatchError(
      `The master key does not match the key used to encrypt this file (expected fingerprint ${recorded}). Wrong key?`
    );
  }
}

export function decryptText(text: string, keyBytes: Buffer): string {
  const parsed = parse(text);
  assertNotAsymmetric(parsed);
  verifyKey(parsed, keyBytes);
  for (const record of parsed.records) {
    if (record.kind !== "entry") {
      continue;
    }
    if (isEncryptedValue(record.value)) {
      const plaintext = decryptValue(keyBytes, record.value, record.key);
      record.value = formatValue(plaintext);
    } else {
      record.value = formatValue(record.value);
    }
  }
  stripManagedComments(parsed);
  return serialize(parsed);
}

export function decryptToObject(text: string, keyBytes: Buffer): Record<string, string> {
  const parsed = parse(text);
  assertNotAsymmetric(parsed);
  verifyKey(parsed, keyBytes);
  const result: Record<string, string> = {};
  for (const record of parsed.records) {
    if (record.kind !== "entry") {
      continue;
    }
    result[record.key] = isEncryptedValue(record.value)
      ? decryptValue(keyBytes, record.value, record.key)
      : record.value;
  }
  return result;
}
