"""High-level orchestration: key resolution and whole-file transforms.

This ties together :mod:`secure_dotenv.crypto` (primitives) and
:mod:`secure_dotenv.parser` (structure) into the operations the CLI and the
runtime loader actually need:

* find the master key (explicit arg -> env var -> local key file),
* encrypt / decrypt an entire file's text while preserving structure,
* embed and verify a key fingerprint so a wrong key fails fast.
"""

from __future__ import annotations

import os
from typing import Dict, Optional

from . import crypto, parser
from .exceptions import (
    KeyFingerprintMismatchError,
    MasterKeyNotFoundError,
)

# --- Well-known names -------------------------------------------------------

KEY_FILE_NAME = ".secure-dotenv.key"
ENV_VAR_NAME = "SECURE_DOTENV_MASTER_KEY"

BANNER = "# Generated by secure-dotenv. DO NOT EDIT VALUES MANUALLY."
METADATA_PREFIX = "# secure-dotenv:"
METADATA_VERSION = "1"


# --- Key resolution ---------------------------------------------------------

def find_key_file(start_dir: Optional[str] = None) -> Optional[str]:
    """Return the path to a local key file, searching upward from ``start_dir``.

    Walks up the directory tree (like git looking for ``.git``) so the tool
    works from subdirectories of a project.
    """
    current = os.path.abspath(start_dir or os.getcwd())
    while True:
        candidate = os.path.join(current, KEY_FILE_NAME)
        if os.path.isfile(candidate):
            return candidate
        parent = os.path.dirname(current)
        if parent == current:
            return None
        current = parent


def resolve_master_key(
    master_key: Optional[str] = None,
    *,
    key_file: Optional[str] = None,
    search_dir: Optional[str] = None,
) -> str:
    """Resolve the master key as a base64 string.

    Resolution order (first match wins):
        1. ``master_key`` argument,
        2. the ``SECURE_DOTENV_MASTER_KEY`` environment variable,
        3. an explicit ``key_file`` path, then a discovered local key file.

    Raises:
        MasterKeyNotFoundError: if no key can be found.
    """
    if master_key:
        return master_key.strip()

    env_value = os.environ.get(ENV_VAR_NAME)
    if env_value and env_value.strip():
        return env_value.strip()

    path = key_file or find_key_file(search_dir)
    if path and os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as fh:
            return fh.read().strip()

    raise MasterKeyNotFoundError(
        "No master key found. Provide one explicitly, set the "
        f"{ENV_VAR_NAME} environment variable, or run `secure-dotenv init` "
        f"to create a local {KEY_FILE_NAME} file."
    )


# --- Metadata ---------------------------------------------------------------

def build_metadata_line(key_bytes: bytes) -> str:
    fp = crypto.key_fingerprint(key_bytes)
    return f"{METADATA_PREFIX} v={METADATA_VERSION} alg={crypto.ALGORITHM} key_fp={fp}"


def parse_metadata(parsed: parser.ParsedEnv) -> Dict[str, str]:
    """Extract the ``# secure-dotenv:`` metadata tokens, if present."""
    for record in parsed.records:
        if record.kind == "comment" and record.raw.strip().startswith(METADATA_PREFIX):
            body = record.raw.strip()[len(METADATA_PREFIX):].strip()
            meta: Dict[str, str] = {}
            for token in body.split():
                if "=" in token:
                    k, v = token.split("=", 1)
                    meta[k] = v
            return meta
    return {}


def _strip_managed_comments(parsed: parser.ParsedEnv) -> None:
    """Remove secure-dotenv's own banner / metadata comments (keep user ones)."""
    kept = []
    for record in parsed.records:
        if record.kind == "comment":
            text = record.raw.strip()
            if text == BANNER or text.startswith(METADATA_PREFIX):
                continue
        kept.append(record)
    parsed.records = kept


# --- Whole-file transforms --------------------------------------------------

def encrypt_text(text: str, key_bytes: bytes) -> str:
    """Encrypt all cleartext values in ``text``; return ``.env.enc`` text."""
    parsed = parser.parse(text)
    _strip_managed_comments(parsed)
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            continue  # idempotent: already encrypted
        record.value = crypto.encrypt_value(key_bytes, record.value, aad=record.key)

    body = parser.serialize(parsed).rstrip("\n")
    parts = [BANNER]
    if body:
        parts.append(body)
    parts.append(build_metadata_line(key_bytes))
    return "\n".join(parts) + "\n"


def verify_key(parsed: parser.ParsedEnv, key_bytes: bytes) -> None:
    """Raise if the file's recorded fingerprint does not match ``key_bytes``."""
    meta = parse_metadata(parsed)
    recorded = meta.get("key_fp")
    if recorded and recorded != crypto.key_fingerprint(key_bytes):
        raise KeyFingerprintMismatchError(
            "The master key does not match the key used to encrypt this file "
            f"(expected fingerprint {recorded}). Wrong key?"
        )


def decrypt_text(text: str, key_bytes: bytes) -> str:
    """Decrypt all encrypted values in ``text``; return cleartext ``.env`` text."""
    parsed = parser.parse(text)
    verify_key(parsed, key_bytes)
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            plaintext = crypto.decrypt_value(key_bytes, record.value, aad=record.key)
            record.value = parser.format_value(plaintext)
        else:
            record.value = parser.format_value(record.value)
    _strip_managed_comments(parsed)
    return parser.serialize(parsed)


def decrypt_to_dict(text: str, key_bytes: bytes) -> Dict[str, str]:
    """Decrypt ``text`` into a ``{name: value}`` mapping, in memory only."""
    parsed = parser.parse(text)
    verify_key(parsed, key_bytes)
    result: Dict[str, str] = {}
    for record in parsed.records:
        if record.kind != "entry":
            continue
        if crypto.is_encrypted_value(record.value):
            result[record.key] = crypto.decrypt_value(
                key_bytes, record.value, aad=record.key
            )
        else:
            result[record.key] = record.value
    return result


# --- Filesystem helpers -----------------------------------------------------

def write_secret_file(path: str, text: str, *, mode: int = 0o600) -> None:
    """Write ``text`` to ``path`` with restrictive (owner-only) permissions."""
    directory = os.path.dirname(os.path.abspath(path))
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
    finally:
        # Re-assert mode in case the file pre-existed with looser perms.
        try:
            os.chmod(path, mode)
        except OSError:
            pass
    _ = directory  # reserved for future atomic-rename hardening
